export const events = {
  CONNECTION: 'connection',
  DISCONNECT: 'disconnect',
  JOIN_ROOM: 'join-room',
  GET_ROOMS: 'get-rooms',
  LEAVE_ROOM: 'leave-room',
  CREATE_ROOM: 'create-room',
  DELETE_ROOM: 'delete-room',
  SEND_MESSAGE: 'send-message',
  RECEIVE_MESSAGE: 'receive-message',
  SEND_TYPING: 'send-typing',
  RECEIVE_TYPING: 'receive-typing',
  START_STREAM: 'start-stream',
  PAUSE_VIDEO: 'pause-video',
  PLAY_VIDEO: 'play-video',
  SEEK_VIDEO: 'seek-video',
  SYNC_VIDEO: 'sync-video',
  END_VIDEO: 'end-video',
} as const;
